#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/edinsonpb/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/node" "/home/edinsonpb/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"